apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - module.yaml

configMapGenerator:
  - name: rabbitmq-address
    env: rabbitmq_address.env

commonLabels:
  app: broker-test-rabbitmq
