apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: module
spec:
  template:
    spec:
      containers:
        - name: module
          env:
            - name: QUEUE_NAME
              value: "builder"
